### ISSUE TITLE
key error when constructing distances in autotst

### ISSUE THREAD

**Issue by sevyharris** [sevyharris/autoscience_workflow#8]
Example reaction 1685
key error 'd12'

```
Constructing reaction in AutoTST...
debug distances are {}
Traceback (most recent call last):
  File "/work/westgroup/harris.se/autoscience/autoscience_workflow/workflow/scripts/kinetics/run_one.py", line 15, in <module>
    kineticfun.run_TS_shell_calc(reaction_index)
  File "/work/westgroup/harris.se/autoscience/autoscience_workflow/workflow/scripts/kinetics/kineticfun.py", line 270, in run_TS_shell_calc
    reaction.ts[direction][0].get_molecules()
  File "/work/westgroup/harris.se/AutoTST/autotst/reaction.py", line 117, in ts
    distance_data=self.distance_data,
  File "/work/westgroup/harris.se/AutoTST/autotst/reaction.py", line 141, in distance_data
    self.generate_distance_data()
  File "/work/westgroup/harris.se/AutoTST/autotst/reaction.py", line 258, in generate_distance_data
    if ((np.isclose(self._distance_data.distances["d12"] + self._distance_data.distances["d23"],
KeyError: 'd12'
```

**Comment by sevyharris** [comment]
Not all of the nodes on the autogenerated tree are populated with distance data, so I rewrote the code to fall up the tree until you find some distance data

**Comment by sevyharris** [comment]
I think I fixed it [here](https://github.com/ReactionMechanismGenerator/AutoTST/commit/31bdb67e8e82a017c985d3597d9d4f80e32ed60e)
