### ISSUE TITLE
Problem identifying species [CH2]C=CC

### ISSUE THREAD

**Issue by sevyharris** [sevyharris/autoscience_workflow#9]
maybe autotst is renaming the species?

```
Reaction index is 720
Failed to get species name for [CH2]C=CC
could not identify species [CH2]C=CC
Traceback (most recent call last):
  File "/work/westgroup/harris.se/autoscience/autoscience_workflow/workflow/scripts/kinetics/setup_arkane_kinetics.py", line 91, in <module>
    species_index = job.smiles2index(species_smiles)
  File "/work/westgroup/harris.se/autoscience/autoscience_workflow/workflow/scripts/thermo/job.py", line 44, in smiles2index
    species_index = species_df[species_df['SMILES'] == species_smiles]['i'].values[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
sbatch: error: Unable to open file run_arkane.sh
C=C[CH]C+[CH2]C=O_C=C=O+CC=CC
Shell optimization already ran
Shell optimization already ran
Shell optimization already ran
Shell optimization already ran
Shell optimization already ran
Shell optimization already ran
0 /work/westgroup/harris.se/autoscience/autoscience/butane/dft/kinetics/reaction_0720/overall/fwd_ts_0000.log
Overall TS optimization already ran for reaction /work/westgroup/harris.se/autoscience/autoscience/butane/dft/kinetics/reaction_0720/overall/fwd_ts_0000.log
0 /work/westgroup/harris.se/autoscience/autoscience/butane/dft/kinetics/reaction_0720/overall/fwd_ts_0002.log
Overall TS optimization already ran for reaction /work/westgroup/harris.se/autoscience/autoscience/butane/dft/kinetics/reaction_0720/overall/fwd_ts_0002.log
0 /work/westgroup/harris.se/autoscience/autoscience/butane/dft/kinetics/reaction_0720/overall/fwd_ts_0005.log
Overall TS optimization already ran for reaction /work/westgroup/harris.se/autoscience/autoscience/butane/dft/kinetics/reaction_0720/overall/fwd_ts_0005.log
[]
starting run_arkane_job for reaction 720 C=C[CH]C+[CH2]C=O_C=C=O+CC=CC
```

**Comment by sevyharris** [comment]
Somehow autotst is turning C=C[CH]C into its resonance structure [CH2]C=CC

**Comment by sevyharris** [comment]
AutoTST can't find a match, so it's looking at resonance structures. It finds a match using the resonance structure, and then changes the species to be that resonance structure. I think I might be going about this the wrong way. I should let AutoTST find the matching reaction using the resonance structure, but then I should also include a reaction describing the conversion from one resonance structure to the other? Part of the problem is I only have C=C[CH]C in my model and not [CH2]C=CC...
